version: "3.8"

services:
   web:
     build: 
        context: ..
        dockerfile: Docker/WebApp/Dockerfile
     image: haya98b/webapp:latest
     ports: 
       - 8080:5000
     volumes:
       - ../code/:/project
     environment:
       WAIT_HOSTS: db:3306
       MYSQL_DATABASE: newdatabase
       MYSQL_HOST: db
     restart: on-failure
   db:
     build:
        context: ..
        dockerfile: Docker/DataBase/Dockerfile
     image: haya98b/mysql:latest
     ports:
       - 3306:3306
     environment:
       MYSQL_ROOT_PASSWORD: root
       MYSQL_DATABASE: newdatabase
     restart: on-failure
     volumes:
       - mysql_data:/var/lib/mysql
volumes:
   mysql_data:

